### ISSUE TITLE
Cannot locate the learnable learning rate

### ISSUE THREAD

**Issue by ghost** [sjoerdvansteenkiste/Neural-EM#13]
Hello,

I have a question about the learning rate implemented in N-EM.
In section A.1 of the appendix of your paper, you mention that "[we] train an additional weight to implement the learning rate that is used to combine the gradient ascent updates into the current parameter estimate." 

I assume from this that the learning rate of the GEM algorithm is learned instead of fixed, but there aren't any more details as to the what network outputs the learning rate at each EM iteration and what are its inputs to this network. Furthermore, I can't seem to locate where in this repo this learnable learning rate is implemented.

I would really appreciate your help.
Thanks in advance :)

**Comment by sjoerdvansteenkiste** [comment]
Hi!

You can find a link to the adaptable learning rate (which is only used for N-EM, but not for RNN-EM) below. It is not outputted by any network, but a trainable var that we back-propagate into.

https://github.com/sjoerdvansteenkiste/Neural-EM/blob/062437c027d1e2e0a8699eb9c798258a6f5b62ba/network.py#L294
