### ISSUE TITLE
Univariate gaussian

### ISSUE THREAD

**Issue by andompesta** [sjoerdvansteenkiste/Neural-EM#3]
Hi,

I saw in your code that you used a univariate Gaussian (or univariate Bernoulli) distribution to compute the pixel probabilities.
I'm wondering if you used the univariate formulation because you assume that each pixel and each channel are independent?

If that is the case, and I want to extend the model to items with a d-dimensional embedding, should I use a d-variate distribution or it wouldn't change much from the univariate formulation?

Cheers,
Sandro

**Comment by sjoerdvansteenkiste** [comment]
Hi,

Yes indeed, we assume that random variables corresponding to pixels are independent given theta (the representation that is the input to the decoder). 

If we were to generalize this to RGB data (eg. multi-channel) than the same formulation can be applied.  However, should probably consider only a single z for each pixel location (i.e. for all channels at that location) such that the mask for each pixel is the same across all channels. 

I interpret your case as extending to a d-dimensional channel for each pixel. Likewise I would consider a univariate gaussian for each dimension and let the representation (theta) take care of any dependencies. Whether you want to consider a separate latent variable for each dimension d or use a single latent variable for each pixel location (shared across the channels, as for RGB) depends on on the particular use-case that you have in mind. 

Sjoerd
